include ActsAsTaggableOn
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.create(first_name: 'Erik', last_name: 'Rumppe', email: 'erumppe@gmail.com', password: 'lippln4z')
Tag.create(name: 'Appetizers')
Tag.create(name: 'BBQ and grilling')
Tag.create(name: 'Beef')
Tag.create(name: 'Bread')
Tag.create(name: 'Breakfast/Brunch')
Tag.create(name: 'Cakes')
Tag.create(name: 'Chicken')
Tag.create(name: 'Cookies')
Tag.create(name: 'Desserts')
Tag.create(name: 'Family')
Tag.create(name: 'Healthy Cooking')
Tag.create(name: 'Holidays')
Tag.create(name: 'Italian')
Tag.create(name: 'Kid-friendly')
Tag.create(name: 'Lifestyle')
Tag.create(name: 'Main Dish')
Tag.create(name: 'Meal ideas')
Tag.create(name: 'Mexican')
Tag.create(name: 'Other ethnic food')
Tag.create(name: 'Pasta')
Tag.create(name: 'Pork')
Tag.create(name: 'Quick and Easy')
Tag.create(name: 'Restaurants')
Tag.create(name: 'Salad')
Tag.create(name: 'Seafood')
Tag.create(name: 'Seasonal Cooking')
Tag.create(name: 'Side-dish')
Tag.create(name: 'Slow Cooker')
Tag.create(name: 'Soups and stews')
Tag.create(name: 'Vegitarian')
Tag.create(name: 'Vegan')
Tag.create(name: 'Paleo')
Tag.create(name: 'Glutten free')